export enum NotificationCategory {
  SYSTEM = "SYSTEM",
  BILLING = "BILLING",
  WEBSITE = "WEBSITE",
  SECURITY = "SECURITY",
  WORKSPACE = "WORKSPACE"
}

export const NotificationTypes = {
  // SYSTEM
  SYSTEM_ALERT: "SYSTEM_ALERT",
  SYSTEM_ANNOUNCEMENT: "SYSTEM_ANNOUNCEMENT",

  // BILLING
  SUBSCRIPTION_CREATED: "SUBSCRIPTION_CREATED",
  SUBSCRIPTION_UPDATED: "SUBSCRIPTION_UPDATED",
  SUBSCRIPTION_PAST_DUE: "SUBSCRIPTION_PAST_DUE",
  SUBSCRIPTION_CANCELED: "SUBSCRIPTION_CANCELED",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  PAYMENT_FAILED: "PAYMENT_FAILED",

  // WEBSITE
  WEBSITE_CREATED: "WEBSITE_CREATED",
  WEBSITE_PUBLISHED: "WEBSITE_PUBLISHED",
  WEBSITE_DOMAIN_VERIFIED: "WEBSITE_DOMAIN_VERIFIED",

  // SECURITY / ACCOUNT
  SECURITY_ALERT: "SECURITY_ALERT",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  EMAIL_VERIFIED: "EMAIL_VERIFIED",

  // WORKSPACE
  WORKSPACE_INVITATION: "WORKSPACE_INVITATION",
  WORKSPACE_ROLE_CHANGED: "WORKSPACE_ROLE_CHANGED",
} as const;

export type NotificationType = keyof typeof NotificationTypes;

// Mapping to categories for preferences
export const NotificationCategoryMap: Record<NotificationType, NotificationCategory> = {
  SYSTEM_ALERT: NotificationCategory.SYSTEM,
  SYSTEM_ANNOUNCEMENT: NotificationCategory.SYSTEM,

  SUBSCRIPTION_CREATED: NotificationCategory.BILLING,
  SUBSCRIPTION_UPDATED: NotificationCategory.BILLING,
  SUBSCRIPTION_PAST_DUE: NotificationCategory.BILLING,
  SUBSCRIPTION_CANCELED: NotificationCategory.BILLING,
  PAYMENT_SUCCESS: NotificationCategory.BILLING,
  PAYMENT_FAILED: NotificationCategory.BILLING,

  WEBSITE_CREATED: NotificationCategory.WEBSITE,
  WEBSITE_PUBLISHED: NotificationCategory.WEBSITE,
  WEBSITE_DOMAIN_VERIFIED: NotificationCategory.WEBSITE,

  SECURITY_ALERT: NotificationCategory.SECURITY,
  PASSWORD_CHANGED: NotificationCategory.SECURITY,
  EMAIL_VERIFIED: NotificationCategory.SECURITY,

  WORKSPACE_INVITATION: NotificationCategory.WORKSPACE,
  WORKSPACE_ROLE_CHANGED: NotificationCategory.WORKSPACE,
};
